### ISSUE TITLE
suggesting osu! Accuracy command

### ISSUE THREAD

**Issue by Apollo-P** [dain98/Minccino#3]
`-acc [300s, 100s, 50s, misses]`

Example usage:

> -acc 346 3 0 1
> Accuracy: 99.14%

You seem to already have [function calculate_acc](https://github.com/dain98/Minccino/blob/c6aca6859cad149f0592a4497da161839f4afbdf/cogs/osu.py#L992), creating this command should not take more work than returning with user arguments.

**Comment by dain98** [comment]
Will get this done in a few.

**Comment by dain98** [comment]
Added! Sorry this took uh 2 weeks longer than usual LOL
