### ISSUE TITLE
unbold map completion or something

### ISSUE THREAD

**Issue by chezbananas** [dain98/Minccino#5]
in the current layout of -recent map completion and accuracy are both bolded and both have percents, so it's easy to confuse the two especially if the play was quit out at the end or something

eg: ![](https://cdn.discordapp.com/attachments/552383253642739731/599712169117876244/score_257286775.png)

**Comment by dain98** [comment]
Changed it, looks a lot better. Good call.
![image](https://user-images.githubusercontent.com/27909219/61209472-d24e5e00-a734-11e9-87ca-e8bb037b3475.png)
